### ISSUE TITLE
help

### ISSUE THREAD

**Issue by huangzongwang** [mattboyer/sqbrite#30]
022-11-14 16:37:14,646 INFO: Processing /www/wwwroot/FTS5IndexMicroMsg_encrypt.db
2022-11-14 16:37:14,647 DEBUG: Loading YAML data for table grouping "Firefox"
2022-11-14 16:37:14,648 DEBUG: Loaded heuristics for "moz_places"
2022-11-14 16:37:14,648 DEBUG: Loading YAML data for table grouping "iOs"
2022-11-14 16:37:14,648 DEBUG: Loaded heuristics for "ZCALLRECORD"
2022-11-14 16:37:14,648 DEBUG: Loaded heuristics for "attachment"
2022-11-14 16:37:14,648 DEBUG: Loaded heuristics for "chat"
2022-11-14 16:37:14,648 DEBUG: Loaded heuristics for "handle"
2022-11-14 16:37:14,648 DEBUG: Loaded heuristics for "message"
2022-11-14 16:37:14,648 DEBUG: No lock-byte page in this file!
2022-11-14 16:37:14,648 DEBUG: SQLite_header(magic=b'SQLite format 3\x00', page_size=4096, write_format=1, read_format=1, reserved_length=0, max_payload_fraction=64, min_payload_fraction=32, leaf_payload_fraction=32, file_change_counter=178, size_in_pages=50161, first_freelist_trunk=0, freelist_pages=0, schema_cookie=114, schema_format=4, default_page_cache_size=0, largest_btree_page=0, text_encoding=1, user_version=0, incremental_vacuum=0, application_id=0, version_valid=178, sqlite_version=3034001)
2022-11-14 16:37:15,161 INFO: Database: <SQLite DB, page count: 50161 | page size: 4096>
2022-11-14 16:37:15,161 DEBUG: This database has no freelist trunk page
2022-11-14 16:37:15,161 WARNING: <SQLite DB, page count: 50161 | page size: 4096> does not have ptrmap pages!
2022-11-14 16:37:15,177 INFO: Parsing overflow pages
2022-11-14 16:37:15,193 INFO: Overflow summary: 0 pages
2022-11-14 16:37:15,193 DEBUG: Parsing cells in table interior cell 1
2022-11-14 16:37:15,193 DEBUG: Parsing cell 0 @ offset 4091
2022-11-14 16:37:15,194 DEBUG: Parsing cell 1 @ offset 4086
2022-11-14 16:37:15,194 DEBUG: Parsing cell 2 @ offset 4081
2022-11-14 16:37:15,194 DEBUG: Parsing cell 3 @ offset 4076
2022-11-14 16:37:15,194 DEBUG: Parsing cells in table leaf cell 2
2022-11-14 16:37:15,194 DEBUG: Parsing cell 0 @ offset 4082
Traceback (most recent call last):
  File "/usr/local/bin/sqbrite", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/sqbrite/sqlite_recover.py", line 289, in main
    subcmd_dispatcher(cli_args)
  File "/usr/local/lib/python3.6/site-packages/sqbrite/sqlite_recover.py", line 184, in subcmd_dispatcher
    return subcmd_actions[arg_ns.subcmd](arg_ns)
  File "/usr/local/lib/python3.6/site-packages/sqbrite/sqlite_recover.py", line 85, in dump_to_csv
    db = _load_db(args.sqlite_path)
  File "/usr/local/lib/python3.6/site-packages/sqbrite/sqlite_recover.py", line 69, in _load_db
    db.populate_btree_pages()
  File "/usr/local/lib/python3.6/site-packages/sqbrite/db.py", line 346, in populate_btree_pages
    page_obj.parse_cells()
  File "/usr/local/lib/python3.6/site-packages/sqbrite/pages.py", line 241, in parse_cells
    self.parse_table_leaf_cells()
  File "/usr/local/lib/python3.6/site-packages/sqbrite/pages.py", line 292, in parse_table_leaf_cells
    integer_key = Varint(bytes(self)[offset:offset+9])
  File "/usr/local/lib/python3.6/site-packages/sqbrite/utils.py", line 44, in __init__
    int.to_bytes(varint_twos_complement, 4, byteorder='big'), 64
OverflowError: int too big to convert

**Comment by mattboyer** [comment]
Hi,

It would be very useful if you could share the `/www/wwwroot/FTS5IndexMicroMsg_encrypt.db` SQLite file you're operating on.

Based on the name and [a bit of research](https://github.com/Tencent/wcdb/issues/870), it appears to be used by WeChat/微信. Be advised that there are currently no heuristics for the files produced by that program, although I'd be delighted to receive contributions.

**Comment by mattboyer** [comment]
Can't reproduce without input SQLite file.
